name = "vlsigpt"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"
 "vars": {
    "NEXT_PUBLIC_SUPABASE_URL": "https://mpvpqkjjxemngurmnjtm.supabase.co",
    "NEXT_PUBLIC_SUPABASE_ANON_KEY": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1wdnBxa2pqeGVtbmd1cm1uanRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MTkyNDcsImV4cCI6MjA2MzQ5NTI0N30.HUSzKnAkiQFIbJhoamjWgMlZeSY9O14WA4gZJx0IaEw",
  },